points = dlmread('example2.txt');

x = points(:, 1);
y = points(:, 2);
% z = points(:, 3);

scatter(x, y, 15, 'filled', 'k')
% scatter3(x, y, z, 15, 'filled', 'k')
axis equal
xlabel('x')
ylabel('y')
% zlabel('z')
title('Nodes generated by FNP algorithm.')
